### ISSUE TITLE
the coefficient m is zero from the if condition

### ISSUE THREAD

**Issue by mehdirezaie** [ashleyjross/LSSanalysis#5]
Hi! It sounds the coefficient `m` is zero from the previous `if statement`.
https://github.com/ashleyjross/LSSanalysis/blob/766fb32daa31798f547c13a5bfea4bd8286d566a/xitools_eboss.py#L270

**Comment by ashleyjross** [comment]
I noticed this yesterday. I just pushed the new version where it should be fixed!
